# Generated by Django 4.2.2 on 2024-05-22 16:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='movie',
        ),
        migrations.AddField(
            model_name='role',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie.movie'),
            preserve_default=False,
        ),
    ]
