# Generated by Django 5.0.6 on 2024-07-05 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, upload_to='category/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=150)),
                ('phone_1', models.CharField(blank=True, max_length=150)),
                ('phone_2', models.CharField(blank=True, max_length=150)),
                ('address_1', models.CharField(blank=True, max_length=150)),
                ('address_2', models.CharField(blank=True, max_length=150)),
                ('avatar', models.ImageField(blank=True, upload_to='service/images/')),
                ('work_time', models.TimeField(blank=True)),
                ('working_days', models.CharField(choices=[('mon', 'Dushanba'), ('tue', 'Seshanba'), ('wed', 'Chorshanba'), ('thu', 'Payshanba'), ('fri', 'Juma'), ('sat', 'Shanba'), ('sun', 'Yakshanba')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('reyting_value', models.IntegerField(default=0)),
                ('payment_method', models.CharField(choices=[('pc', 'Plastik karta'), ('ca', 'Naqd pul'), ('bt', 'Bank oʻtkazmasi')], max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_service', to='main.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('comment', models.CharField(blank=True, max_length=350)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='main.service')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='service/images/')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='main.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='main.category')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='service_types',
            field=models.ManyToManyField(to='main.servicetype'),
        ),
    ]
