# Generated by Django 5.0.6 on 2024-07-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('pc', 'Plastik karta'), ('ca', 'Naqd pul'), ('bt', 'Bank oʻtkazmasi')], max_length=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='working_days',
            field=models.CharField(blank=True, choices=[('mon', 'Dushanba'), ('tue', 'Seshanba'), ('wed', 'Chorshanba'), ('thu', 'Payshanba'), ('fri', 'Juma'), ('sat', 'Shanba'), ('sun', 'Yakshanba')], max_length=20),
        ),
    ]
