# Generated by Django 5.0.6 on 2024-07-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_service_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='work_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
