# Generated by Django 5.0.6 on 2024-07-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_service_work_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='work_time',
            new_name='work_time_end',
        ),
        migrations.AddField(
            model_name='service',
            name='work_time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
