# Generated by Django 4.2.5 on 2023-09-12 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player',
            new_name='Players',
        ),
    ]
