# Generated by Django 4.2.5 on 2023-09-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_rename_player_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='players',
            name='number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='players',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='players',
            name='weight',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
