# Generated by Django 4.2.5 on 2023-09-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_alter_players_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
