# Generated by Django 4.2.14 on 2024-12-13 11:31

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_bith', models.DateField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('position', models.CharField(choices=[('striker', 'Striker'), ('defender', 'Defender'), ('midfielder', 'Midfielder'), ('goalkeeper', 'Goalkeeper')], max_length=100)),
                ('height', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players', to='main.club')),
            ],
        ),
    ]
