# Generated by Django 4.2.14 on 2024-12-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
