# Generated by Django 4.2.2 on 2024-05-13 17:25

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Tur nomini kirit')),
                ('logo', models.ImageField(blank=True, upload_to='logos/tournament/')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('coach', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Tur nomini kirit')),
                ('logo', models.ImageField(blank=True, upload_to='logos/tournament/')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('last_winner', models.CharField(blank=True, max_length=250)),
                ('description', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Tur nomini kirit')),
                ('image', models.ImageField(blank=True, upload_to='player/images/')),
                ('origin_name', models.CharField(max_length=250, verbose_name='Tur nomini kirit')),
                ('position', models.CharField(choices=[('gk', 'GoalKeeper'), ('df', 'Deffender'), ('mdf', 'Middle deffender'), ('fw', 'Forward'), ('st', 'Striker')], max_length=250)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('date_of_birth', models.DateField(blank=True)),
                ('height', models.PositiveSmallIntegerField(default=0)),
                ('weight', models.PositiveSmallIntegerField(default=0)),
                ('transfer_summa', models.FloatField(blank=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='players.club')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='players.tournament'),
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='players.club')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
                ('tournaments', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='players.tournament')),
            ],
        ),
    ]
