# Generated by Django 4.2.2 on 2024-05-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Klub nomini kirit'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Player name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='origin_name',
            field=models.CharField(max_length=250, verbose_name='Origin name'),
        ),
    ]
