# Generated by Django 4.2.2 on 2024-06-10 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 6, 10, 16, 33, 4, 787089, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
